#docker-compose up --build
version: "2.4"
services:
  app:
    build:
      context: .
      args:
        - CONTENT_DIR=./
    # image: registry.vathes.com/datajoint/${SITE}:${VERSION}
    platform: linux/amd64
    ports:
      - "80:80"